### ISSUE TITLE
ModuleNotFoundError: No module named 'qdrant_client'

### ISSUE THREAD

**Issue by shreyansh-chouriya** [Ashish-Abraham/QueReyDB#1]
Hi, 
After running your code getting error as ModuleNotFoundError: No module named 'qdrant_client'. 
I have installed all the requirements correctly.

**Comment by Ashish-Abraham** [comment]
Please check again. The library is qdrant-client, which you can install using
```pip install qdrant-client ```
Also try 
```pip install -qU langchain-qdrant```

You may have to upgrade to latest versions also.
